### ISSUE TITLE
Owned Shadow Properties: design considerations

### ISSUE THREAD

**Issue by IdeaHunter** [aspnet/EntityFramework.Docs#1463]
I have tried to model a workaroud of not yet implemented feature many-to-many relationship #1368 trough owned shadow properties via fluent api and got an error message that at first sight _seems_ conflict with definition of shadow properties given in documentation.
From documentation about shadow properties

> Shadow properties are properties that are not defined in your .NET entity class but are defined for that entity type in the EF Core model. 

but the message i've got tells me that shadow property dont have correspoding CLR property. 

This leads me to a question:
_Is there anything wrong with trying to make a shadow owned properties or im misunderstool the thing i have read in documentation?_

Im 100% understand my use case is silly, im just seeing owned properties as a way to do a table splitting and shadow properties as an instrument of keeping underlying EF Core mechanics away from POCO that represents business data and trying to glue then together

More details:
```
Exception message:
The navigation property 'PropertyRelations' cannot be added to the entity type 'Entity' because there is no corresponding CLR property on the underlying type and navigations properties cannot be added to shadow 
Stack trace:
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.PrincipalToDependent(String name, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder targetEntityTypeBuilder, Nullable`1 navigationToTarget, Nullable`1 inverseNavigation, Boolean setTargetAsPrincipal, ConfigurationSource configurationSource, Nullable`1 required)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Owns(TypeIdentity& targetEntityType, PropertyIdentity navigation, Nullable`1 inverse, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Owns(Type targetEntityType, String navigationName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsManyBuilder(TypeIdentity& ownedType, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsMany(Type ownedType, String navigationName, Action`1 buildAction)
   at DataAccessLayer.SQL.AppDbContext.OnModelCreating(ModelBuilder modelBuilder)
```

### Steps to reproduce
First i defined shadow property then i tried to use .OwnsMany to model many to many relationship trough helper object. Im using reflection since i have a lot of model that have many to relationship and i personally dont like copy paste approach

```c#
var model = modelBuilder.Entity(modelType);

var propType = classProp.PropertyType;
var propName = classProp.Name;

model.Ignore(propName);

var newShadowProp = $"{propName}Relations";
var newShadowPropType = typeof(ICollection<>)
    .MakeGenericType(new[] { typeof(ManyToManyRelation) });

model.Property(newShadowPropType , newShadowProp);

model.OwnsMany(typeof(ManyToManyRelation), newShadowProp, a =>
{
       var tableName = allModelTypes[modelType];
       a.HasForeignKey(nameof(ManyToManyRelation.SourceId));
       a.HasForeignKey(nameof(ManyToManyRelation.TargetId));
       a.HasKey(nameof(ManyToManyRelation.SourceId), nameof(ManyToManyRelation.TargetId));
       a.ToTable($"{tableName}_{classProp.Name}");
}).HasOne(propType)
       .WithMany()
       .HasForeignKey(nameof(ManyToManyRelation.TargetId));

model.HasMany(typeof(ManyToManyRelation), newShadowProp)
      .WithOne()
      .HasForeignKey(nameof(ManyToManyRelation.SourceId));
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012 R2
IDE: (e.g. Visual Studio 2017 15.8.9)

**Comment by ajcvickers** [comment]
Duplicate f ##1460
