### ISSUE TITLE
Problem with Identity Key Columns

### ISSUE THREAD

**Issue by tdyrkacz** [aspnet/EntityFramework.Docs#1806]
I have a problem with latest version 3.0 of core entity framework. When i try to use the database context i get the error that my table has more than one identity key when in fact it has none. It is a table where the PK is made up of multiple foreign keys to other tables where those columns are identity columns.

This worked fine in 2.2.6 I already tried re-scaffolding my database.

Error:

System.InvalidOperationException: The properties 'InstrumentFieldData.DataFeedKey', 'InstrumentFieldData.InstrumentKey', 'InstrumentFieldData.FieldKey', 'InstrumentFieldData.ContextPatternKey' are configured to use 'Identity' value generator and are mapped to the same table 'MarketData.InstrumentFieldData'. Only one column per table can be configured as 'Identity'. Call 'ValueGeneratedNever' for properties that should not use 'Identity'.
  Stack Trace: 
    at SqlServerModelValidator.ValidateSharedColumnsCompatibility(IReadOnlyList`1 mappedTypes, String tableName, IDiagnosticsLogger`1 logger)
    at RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
    at RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
    at SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview of Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/#feedback)
* Content Source: [entity-framework/core/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by tdyrkacz** [comment]
realized it's in the wrong area. Moving to core product issues.

**Comment by tdyrkacz** [comment]
moving issue to core product
